/**
 * The seven shapes, their four orientations, and the wall kicks that let a
 * rotation squeeze into a space the naive turn would not fit.
 *
 * Orientations are generated by rotating the spawn shape inside its own square
 * box rather than being written out four times each. One rotation function to
 * check, and no chance of a typo in the twenty-eighth hand-entered layout.
 *
 * The kick tables are the published Super Rotation System ones, reproduced in
 * their usual `+y is up` convention so they can be compared against the spec
 * line by line. {@link kicksFor} negates `dy` on the way out, because the buffer
 * counts rows downward.
 */
import type { PieceKind, Rotation } from './types'

/** A cell offset inside a piece's box, or a kick translation. */
export interface Offset {
  x: number
  y: number
}

/**
 * Box side per shape. `I` needs four columns to hold its flat orientation. `O`
 * gets a tight 2x2, which is what makes it turn onto itself: rotating a full
 * box maps the set of cells back to the same set, so the square never drifts
 * and needs no special case anywhere downstream.
 */
const BOX: Record<PieceKind, number> = {
  I: 4,
  O: 2,
  T: 3,
  S: 3,
  Z: 3,
  J: 3,
  L: 3,
}

/** Spawn layouts, as filled cells inside each shape's box. */
const SPAWN: Record<PieceKind, readonly Offset[]> = {
  I: [
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 3, y: 1 },
  ],
  O: [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
  ],
  T: [
    { x: 1, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
  ],
  S: [
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
  ],
  Z: [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
  ],
  J: [
    { x: 0, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
  ],
  L: [
    { x: 2, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 1 },
    { x: 2, y: 1 },
  ],
}

/** One quarter turn clockwise inside a `size`-square box. */
function rotateCW(cells: readonly Offset[], size: number): Offset[] {
  return cells.map((c) => ({ x: size - 1 - c.y, y: c.x }))
}

/** Every shape's four orientations, built once at module load. */
const CELLS: Record<PieceKind, readonly (readonly Offset[])[]> = (() => {
  const out = {} as Record<PieceKind, readonly (readonly Offset[])[]>
  for (const kind of Object.keys(SPAWN) as PieceKind[]) {
    const size = BOX[kind]
    const rots: Offset[][] = [SPAWN[kind].map((c) => ({ ...c }))]
    for (let r = 1; r < 4; r++) rots.push(rotateCW(rots[r - 1], size))
    out[kind] = rots
  }
  return out
})()

/** The filled cells of `kind` at `rot`, as offsets inside its box. */
export function pieceCells(kind: PieceKind, rot: Rotation): readonly Offset[] {
  return CELLS[kind][rot]
}

/** Side of `kind`'s bounding box, in cells. */
export function pieceBox(kind: PieceKind): number {
  return BOX[kind]
}

/** Every shape, in the fixed order a bag is built from. */
export const PIECE_KINDS: readonly PieceKind[] = [
  'I',
  'O',
  'T',
  'S',
  'Z',
  'J',
  'L',
]

/** The four corners of a `T` box, used to judge a twist. */
export const T_CORNERS: readonly Offset[] = [
  { x: 0, y: 0 },
  { x: 2, y: 0 },
  { x: 0, y: 2 },
  { x: 2, y: 2 },
]

/**
 * The two corners a `T` points its flat back away from, per orientation. A
 * twist counts as full when both of these are filled, and mini when only one
 * is. Indexed by rotation.
 */
export const T_FRONT_CORNERS: readonly (readonly Offset[])[] = [
  [
    { x: 0, y: 0 },
    { x: 2, y: 0 },
  ],
  [
    { x: 2, y: 0 },
    { x: 2, y: 2 },
  ],
  [
    { x: 0, y: 2 },
    { x: 2, y: 2 },
  ],
  [
    { x: 0, y: 0 },
    { x: 0, y: 2 },
  ],
]

/**
 * A quarter-turn transition, keyed `from>to`.
 *
 * Only the eight adjacent turns exist. A half turn is not a single rotation and
 * has no published kick table, so listing the pairs beats deriving all sixteen
 * from `Rotation` and leaving half of them unfillable.
 */
type KickKey = '0>1' | '1>0' | '1>2' | '2>1' | '2>3' | '3>2' | '3>0' | '0>3'

/** Kicks for every shape but `I` and `O`, in the published `+y is up` form. */
const KICKS_JLSTZ: Record<KickKey, readonly Offset[]> = {
  '0>1': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: -1, y: 1 },
    { x: 0, y: -2 },
    { x: -1, y: -2 },
  ],
  '1>0': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: -1 },
    { x: 0, y: 2 },
    { x: 1, y: 2 },
  ],
  '1>2': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: -1 },
    { x: 0, y: 2 },
    { x: 1, y: 2 },
  ],
  '2>1': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: -1, y: 1 },
    { x: 0, y: -2 },
    { x: -1, y: -2 },
  ],
  '2>3': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 0, y: -2 },
    { x: 1, y: -2 },
  ],
  '3>2': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: -1, y: -1 },
    { x: 0, y: 2 },
    { x: -1, y: 2 },
  ],
  '3>0': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: -1, y: -1 },
    { x: 0, y: 2 },
    { x: -1, y: 2 },
  ],
  '0>3': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 0, y: -2 },
    { x: 1, y: -2 },
  ],
}

/** `I` kicks further and needs its own table. */
const KICKS_I: Record<KickKey, readonly Offset[]> = {
  '0>1': [
    { x: 0, y: 0 },
    { x: -2, y: 0 },
    { x: 1, y: 0 },
    { x: -2, y: -1 },
    { x: 1, y: 2 },
  ],
  '1>0': [
    { x: 0, y: 0 },
    { x: 2, y: 0 },
    { x: -1, y: 0 },
    { x: 2, y: 1 },
    { x: -1, y: -2 },
  ],
  '1>2': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: 2, y: 0 },
    { x: -1, y: 2 },
    { x: 2, y: -1 },
  ],
  '2>1': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: -2, y: 0 },
    { x: 1, y: -2 },
    { x: -2, y: 1 },
  ],
  '2>3': [
    { x: 0, y: 0 },
    { x: 2, y: 0 },
    { x: -1, y: 0 },
    { x: 2, y: 1 },
    { x: -1, y: -2 },
  ],
  '3>2': [
    { x: 0, y: 0 },
    { x: -2, y: 0 },
    { x: 1, y: 0 },
    { x: -2, y: -1 },
    { x: 1, y: 2 },
  ],
  '3>0': [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: -2, y: 0 },
    { x: 1, y: -2 },
    { x: -2, y: 1 },
  ],
  '0>3': [
    { x: 0, y: 0 },
    { x: -1, y: 0 },
    { x: 2, y: 0 },
    { x: -1, y: 2 },
    { x: 2, y: -1 },
  ],
}

/** `O` turns onto itself, so it has nowhere to kick to. */
const KICKS_O: readonly Offset[] = [{ x: 0, y: 0 }]

/** The published tables flipped into buffer coordinates, once at load. */
function toBufferSpace(
  table: Record<KickKey, readonly Offset[]>,
): Record<KickKey, readonly Offset[]> {
  const out = {} as Record<KickKey, readonly Offset[]>
  for (const key of Object.keys(table) as KickKey[]) {
    // `-0` is a distinct value from `0` under `Object.is`, and a kick of
    // negative zero would compare unequal to the identity translation.
    out[key] = table[key].map((o) => ({ x: o.x, y: o.y === 0 ? 0 : -o.y }))
  }
  return out
}
const FLIPPED_JLSTZ = toBufferSpace(KICKS_JLSTZ)
const FLIPPED_I = toBufferSpace(KICKS_I)

/**
 * Translations to try, in order, when turning `kind` from `from` to `to`. The
 * first that leaves the piece in a legal cell wins, and the plain `(0, 0)`
 * entry is always first so an unobstructed turn never displaces the piece.
 *
 * In buffer coordinates, so `y` grows downward.
 */
export function kicksFor(
  kind: PieceKind,
  from: Rotation,
  to: Rotation,
): readonly Offset[] {
  if (kind === 'O') return KICKS_O
  const table = kind === 'I' ? FLIPPED_I : FLIPPED_JLSTZ
  const entry: readonly Offset[] | undefined = table[`${from}>${to}` as KickKey]
  // Only quarter turns are tabled. Anything else falls back to turning in
  // place, which either fits or fails cleanly rather than throwing.
  return entry ?? KICKS_O
}

/**
 * Column the piece's box starts at when it enters a `cols`-wide buffer.
 *
 * Centres the shape's own occupied width rather than its box, so the square and
 * the flat four both come in over the middle. On the standard ten-wide buffer
 * this is the familiar placement: three-wide shapes on columns 3 to 5, `I` on 3
 * to 6, the square on 4 and 5.
 */
export function spawnColumn(kind: PieceKind, cols = 10): number {
  const cells = pieceCells(kind, 0)
  const minX = Math.min(...cells.map((c) => c.x))
  const maxX = Math.max(...cells.map((c) => c.x))
  const width = maxX - minX + 1
  return Math.floor((cols - width) / 2) - minX
}
