// Debug gizmo line program (WGSL source of truth, GLSL ES 300 generated by
// crates/shader-gen via naga). World-space endpoints projected by the 3D
// camera's view-projection. Per-vertex color passes through, premultiplied in
// the fragment stage to match the engine's premultiplied framebuffer. Drawn as
// a line list (set on the pipeline, not here).
//
// Bindings: a_position/a_color at LOC_POSITION/LOC_COLOR (0/1). The view-proj
// block at CAMERA3D_UBO_BINDING (1). The projection matrix targets GL clip-Z,
// and GLSL is generated with the coordinate space kept as authored.

struct DebugCam {
  viewProj: mat4x4<f32>,
};
@group(0) @binding(1) var<uniform> cam: DebugCam;

struct VOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) color: vec4<f32>,
};

@vertex
fn vs_main(@location(0) a_position: vec3<f32>, @location(1) a_color: vec4<f32>) -> VOut {
  var out: VOut;
  out.pos = cam.viewProj * vec4<f32>(a_position, 1.0);
  out.color = a_color;
  return out;
}

@fragment
fn fs_main(in: VOut) -> @location(0) vec4<f32> {
  return vec4<f32>(in.color.rgb * in.color.a, in.color.a);
}
