// Shape program (WGSL source of truth, GLSL ES 300 generated by
// crates/shader-gen via naga). One instanced unit quad covers three shape
// families selected by shapeType (a_shape.x): textured (text + atlas sprites),
// circle SDF, and rounded-box SDF, so text, sprites, and vector shapes share
// one blend-only batch. Each vertex branch positions the quad for its family in
// device px. The fragment branch evaluates the matching SDF or texture sample.
//
// Textured instances pick a fixed-unit texture (atlas or label page) via
// texIndex. GLSL ES 3.00 forbids indexing a sampler array by a non-uniform
// expression, and WGSL forbids `textureSample` under non-uniform control flow,
// so both pages are sampled unconditionally and selected (identical result).
//
// Bindings match batchLayout.ts: attributes at LOC_SHAPE_* (0..9), Frame at
// FRAME_UBO_BINDING (0), u_texAtlas at unit 0, u_texLabel at unit 1.

struct Frame {
  proj: mat3x3<f32>,
};
@group(0) @binding(0) var<uniform> frame: Frame;

@group(1) @binding(0) var u_texAtlas: texture_2d<f32>;
@group(1) @binding(16) var u_texAtlasSamp: sampler;
@group(1) @binding(1) var u_texLabel: texture_2d<f32>;
@group(1) @binding(17) var u_texLabelSamp: sampler;

struct VOut {
  @builtin(position) pos: vec4<f32>,
  @location(0) @interpolate(flat) shapeType: i32,
  @location(1) @interpolate(flat) texIndex: f32,
  @location(2) uv: vec2<f32>,                  // textured
  @location(3) tint: vec4<f32>,                // textured
  @location(4) worldPos: vec2<f32>,            // circle (device px)
  @location(5) @interpolate(flat) center: vec2<f32>,  // circle
  @location(6) @interpolate(flat) radius: f32,        // circle
  @location(7) @interpolate(flat) dash: vec2<f32>,    // circle (dashStart, dashPeriod)
  @location(8) local: vec2<f32>,               // round-rect (centered local)
  @location(9) @interpolate(flat) half: vec2<f32>,    // round-rect half extents
  @location(10) @interpolate(flat) radii: vec4<f32>,  // round-rect radii
  @location(11) @interpolate(flat) strokeWidth: f32,  // circle + round-rect
  @location(12) @interpolate(flat) colorFill: vec4<f32>,
  @location(13) @interpolate(flat) colorStroke: vec4<f32>,
};

@vertex
fn vs_main(
  @location(0) a_unit: vec2<f32>,
  @location(1) a_mCol0: vec2<f32>,
  @location(2) a_mCol1: vec2<f32>,
  @location(3) a_mTranslate: vec2<f32>,
  @location(4) a_shape: vec4<f32>,       // (shapeType, feather, texIndex, pad)
  @location(5) a_params: vec4<f32>,      // circle (radius, stroke, dashStart, dashPeriod) / rrect (halfW, halfH, stroke, _)
  @location(6) a_radii: vec4<f32>,       // round-rect corner radii (tl, tr, br, bl)
  @location(7) a_srcRect: vec4<f32>,     // textured (u0, v0, u1, v1)
  @location(8) a_colorFill: vec4<f32>,   // premultiplied RGBA
  @location(9) a_colorStroke: vec4<f32>, // premultiplied RGBA
) -> VOut {
  var out: VOut;
  let shape = i32(a_shape.x + 0.5);
  out.shapeType = shape;
  out.texIndex = a_shape.z;
  out.colorFill = a_colorFill;
  out.colorStroke = a_colorStroke;

  var p: vec2<f32>;
  if (shape == 1) {
    // Circle: center + (unit-0.5)*2*outerRadius.
    let center = a_mTranslate;
    let radius = a_params.x;
    let strokeWidth = a_params.y;
    let outerRadius = radius + strokeWidth * 0.5 + 1.0;
    p = center + (a_unit - vec2<f32>(0.5)) * 2.0 * outerRadius;
    out.worldPos = p;
    out.center = center;
    out.radius = radius;
    out.strokeWidth = strokeWidth;
    out.dash = a_params.zw;
  } else if (shape == 2) {
    // Round-rect: local centered space + affine.
    let halfExt = a_params.xy;
    let feather = a_shape.y;
    let local = (a_unit - vec2<f32>(0.5)) * 2.0 * (halfExt + feather);
    p = a_mTranslate + a_mCol0 * local.x + a_mCol1 * local.y;
    out.local = local;
    out.half = halfExt;
    out.radii = a_radii;
    out.strokeWidth = a_params.z;
  } else {
    // Textured: affine quad, sample srcRect × tint.
    p = a_mCol0 * a_unit.x + a_mCol1 * a_unit.y + a_mTranslate;
    out.uv = mix(a_srcRect.xy, a_srcRect.zw, a_unit);
    out.tint = a_colorFill;
  }

  let clip = frame.proj * vec3<f32>(p, 1.0);
  out.pos = vec4<f32>(clip.xy, 0.0, 1.0);
  return out;
}

// Signed distance to a rounded box. `r` = (tl, tr, br, bl) corner radii.
fn sdRoundBox(p: vec2<f32>, b: vec2<f32>, r: vec4<f32>) -> f32 {
  let rr = select(r.xw, r.yz, p.x > 0.0);
  let radius = select(rr.x, rr.y, p.y > 0.0);
  let q = abs(p) - b + vec2<f32>(radius);
  return min(max(q.x, q.y), 0.0) + length(max(q, vec2<f32>(0.0))) - radius;
}

// Analytic AA coverage from a signed distance via its screen-space gradient.
fn coverage(d: f32) -> f32 {
  return clamp(0.5 - d / max(fwidth(d), 1e-4), 0.0, 1.0);
}

@fragment
fn fs_main(in: VOut) -> @location(0) vec4<f32> {
  var outColor: vec4<f32>;
  if (in.shapeType == 1) {
    // Circle SDF.
    let delta = in.worldPos - in.center;
    let dist = length(delta);
    let fillAlpha = 1.0 - smoothstep(in.radius - 0.5, in.radius + 0.5, dist);
    let fill = in.colorFill * fillAlpha;
    var stroke = vec4<f32>(0.0);
    if (in.strokeWidth > 0.0) {
      let strokeHalf = in.strokeWidth * 0.5;
      let outer = in.radius + strokeHalf;
      let inner = in.radius - strokeHalf;
      let outerEdge = 1.0 - smoothstep(outer - 0.5, outer + 0.5, dist);
      let innerEdge = smoothstep(inner - 0.5, inner + 0.5, dist);
      var strokeAlpha = outerEdge * innerEdge;
      let dashPeriod = in.dash.y;
      if (dashPeriod > 0.0 && strokeAlpha > 0.0) {
        let dashStart = in.dash.x;
        let dashOnLen = dashPeriod * 0.5;
        let angle = atan2(delta.y, delta.x);
        let TWO_PI = 6.28318530718;
        let wrap = select(angle, angle + TWO_PI, angle < 0.0);
        let arcPos = wrap * in.radius;
        let s = dashStart + arcPos;
        let phase = s - dashPeriod * floor(s / dashPeriod);
        let off = smoothstep(dashOnLen - 0.5, dashOnLen + 0.5, phase);
        strokeAlpha = strokeAlpha * (1.0 - off);
      }
      stroke = in.colorStroke * strokeAlpha;
    }
    outColor = stroke + fill * (1.0 - stroke.a);
    if (outColor.a <= 0.0) {
      discard;
    }
  } else if (in.shapeType == 2) {
    // Round-rect SDF.
    let d = sdRoundBox(in.local, in.half, in.radii);
    let fill = in.colorFill * coverage(d);
    var stroke = vec4<f32>(0.0);
    if (in.strokeWidth > 0.0) {
      let sd = abs(d) - in.strokeWidth * 0.5;
      stroke = in.colorStroke * coverage(sd);
    }
    outColor = stroke + fill * (1.0 - stroke.a);
    if (outColor.a <= 0.0) {
      discard;
    }
  } else {
    // Textured: both pages sampled, then selected by texIndex × tint.
    let atlasTexel = textureSample(u_texAtlas, u_texAtlasSamp, in.uv);
    let labelTexel = textureSample(u_texLabel, u_texLabelSamp, in.uv);
    let texel = select(labelTexel, atlasTexel, in.texIndex < 0.5);
    outColor = texel * in.tint;
  }
  return outColor;
}
